name: NemeChess Open Beta

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build .NET project
        working-directory: 'NemeChess2'
        run: dotnet build --configuration Release

      - name: Publish .NET project
        working-directory: 'NemeChess2'
        run: dotnet publish --configuration Release --output build_output

      - name: Create ZIP Folder
        run: Compress-Archive -Path "NemeChess2/build_output" -DestinationPath "NemeChess2/build_output/release.zip"
        shell: pwsh

      - name: Print Updated GitHub Token
        run: echo ${{ secrets.GH_TOKEN }}

      - name: Configure GitHub CLI
        run: gh config set -h github.com github.token "${{ secrets.GH_TOKEN }}"

      - name: Set Repository Context
        run: echo "::set-env name=GITHUB_REPOSITORY::hristo10000/NemeChess2"

      - name: Release build artifacts
        working-directory: 'NemeChess2'
        run: gh release create v1.0 build_output/release.zip --title "NemeChess Release v1.0" --notes "Release notes for v1.0"
