name: NemeChess Open Beta

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

   defaults:
      run:
        working-directory: 'NemeChess2'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build .NET project
        run: dotnet build --configuration Release

      - name: Publish .NET project
        run: dotnet publish --configuration Release --output build_output

      - name: Create ZIP Folder
        run: |
          Compress-Archive -Path "build_output" -DestinationPath "build_output/release.zip"
        shell: pwsh

      - name: Set working directory to NemeChess2
        run: cd NemeChess2

      - name: Release build artifacts
        run: gh release create v1.0 ../build_output/release.zip
        env:
          GH_TOKEN: ${{ github.token }}