name: NemeChess Open Beta

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build .NET project
        working-directory: 'NemeChess2'
        run: dotnet build --configuration Release

      - name: Publish .NET project
        working-directory: 'NemeChess2'
        run: dotnet publish --configuration Release --output build_output

      - name: Create ZIP Folder
        run: Compress-Archive -Path "NemeChess2/build_output" -DestinationPath "NemeChess2/build_output/release.zip"
        shell: pwsh

      - name: Release build artifacts
        working-directory: 'NemeChess2'
        run: gh release create v1.0 build_output/release.zip
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
